### ISSUE TITLE
Contact section BUG. Page gets broken when click send with empty email field

### ISSUE THREAD

**Issue by dkurganskii** [RyanFitzgerald/devportfolio#103]
Scroll down to Get in Touch section > leave email field empty > type anything in the message field  and click send

Actual: page gets broken. Try to scroll down and you see lots of empty space. It gets fixed after you refresh the page

**Comment by JaiRelan** [comment]
Hey, 
I'm not sure about the exact way to fix your issues, but I may have a handy alternative. The way I did it was that I created a [Typeform](http://typeform.com/) and embedded it. [Check this link out. ](https://help.typeform.com/hc/en-us/articles/360029249212-Embed-your-typeform)

Once you get the HTML, you can simply delete lines [223](https://github.com/RyanFitzgerald/devportfolio/blob/master/index.html#L224) to [230](https://github.com/RyanFitzgerald/devportfolio/blob/master/index.html#L230) and replace it with the code Typeform would've given you.

This worked in my case... Hope it helped :D

**Comment by RyanFitzgerald** [comment]
The contact section is just a placeholder, you can choose to setup Formspree or go with your own solution like Typeform (thanks @JaiRelan!). The error is likely happening because it appears Formspree have updated their API to now require an account and you're given a form ID instead. I'll update the docs around that.
