### ISSUE TITLE
project image not loading on mobile sites

### ISSUE THREAD

**Issue by arun-nemani** [RyanFitzgerald/devportfolio#56]
Great work!
I added several 300x300 project images and they render on desktops, but not mobile.
How would I fix this?

**Comment by RyanFitzgerald** [comment]
Thank you! This is actually the intended functionality to preserve space on mobile. If you want to have them show, you can remove the portion of the media query on line 961-963 in `/scss/styles.scss` and recompile via `npm run watch`. You may need to tweak styles a bit to center the image or something along those lines since they weren't styled for mobile.

Hope that helps and feel free to re-open if you need help or that doesn't fix it!

**Comment by arun-nemani** [comment]
Thanks alot, this helps!

**Comment by mscheel** [comment]
I realize this is closed, but maybe someone will respond anyways and it will help future lookers.

The solution references line 961-963 but the current version of [styles.scss](https://github.com/RyanFitzgerald/devportfolio/blob/master/css/styles.css) only has 13 lines, so it isn't obvious where the change should be made.  Has anyone implemented this and can direct me to a fork of styles.scss, that maybe even has the image centering Ryan mentioned?
